# fly.toml file generated for deno-website2 on 2021-03-03T04:22:36+01:00

app = "deno-website2"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "deno"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 950

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    port = "8080"
    restart_limit = 5
    timeout = "2s"
